extends Node

## DEPRECATED: GameConstants is now merged into GameCore
## This file provides backward compatibility only
## Use "Master", "player", etc. instead

const GAME_VERSION := "0.9.5-beta"

const BUS_MASTER := "Master"
const BUS_SFX := "SFX"
const BUS_MUSIC := "Music"
const BUS_VOICE := "Voice"
const BUS_AMBIENT := "Ambient"
const GROUP_PLAYER := "player"
const GROUP_ENEMIES := "enemies"
const GROUP_PROJECTILES := "projectiles"
const GROUP_ITEMS := "items"
const GROUP_INTERACTABLE := "interactable"
const GROUP_INTERACTABLES := "interactables"
const GROUP_LOOTABLE := "lootable"
const GROUP_DAMAGEABLE := "damageable"
const GROUP_DESTRUCTIBLE := "destructible"
const GROUP_HITTABLE := "hittable"
const GROUP_PUSHABLE := "pushable"
const GROUP_SPAWN_PLAYER := "spawn_player"
const GROUP_SPAWN_ENEMY := "spawn_enemy"
const GROUP_SPAWN_ITEM := "spawn_item"
const GROUP_LEVEL_ROOT := "level_root"
const GROUP_PROPS := "props"
const GROUP_CRATES := "crates"
const GROUP_SECRETS := "secrets"
const GROUP_LADDERS := "ladders"
const GROUP_ROPES := "ropes"
const GROUP_HORIZONTAL_LADDERS := "horizontal_ladders"
const GROUP_TRAVERSABLE := "traversable"
const GROUP_GIBS := "gibs"
const GROUP_ORGANS := "organs"
const GROUP_DISMEMBERED_LIMBS := "dismembered_limbs"
const GROUP_BLOOD_DROPLETS := "blood_droplets"
const GROUP_WEAPON_RACKS := "weapon_racks"
const GROUP_TREASURE_CHESTS := "treasure_chests"
const GROUP_MILITARY_CHESTS := "military_chests"
const GROUP_HIDDEN_STASHES := "hidden_stashes"
const GROUP_CORPSE_PILES := "corpse_piles"
const GROUP_BREAKABLE_PROPS := "breakable_props"
const GROUP_LOOT_PROP_SPAWNERS := "loot_prop_spawners"
const GROUP_MOUSE_STEALERS := "mouse_stealers"
const GROUP_COMPASS_BAR := "compass_bar"
const GROUP_SKILL_TREE_UI := "skill_tree_ui"
const GROUP_MOD_MANAGER_UI := "mod_manager_ui"
const GROUP_TRAVERSAL_HINT_DISPLAY := "traversal_hint_display"
const GROUP_MOD_LOADER := "mod_loader"
const GROUP_TARGETING_SYSTEM := "targeting_system"
const GROUP_LOD_MANAGER := "lod_manager"
const PATH_WEAPONS := "res://game/weapons/"
const PATH_EFFECTS := "res://game/scenes/effects/"
const PATH_ENTITIES := "res://game/entities/"
const PATH_PROJECTILES := "res://game/entities/projectiles/"
const PATH_ITEMS := "res://game/scenes/items/"
const PATH_PROPS := "res://game/world/actors/props/"
const PATH_UI := "res://game/ui/"
const PATH_AUDIO := "res://game/art/audio/"
const PATH_CFG := "res://game/config/"
const CFG_AUDIO := "res://game/config/gameplay/audio.json5"
const CFG_GAMEPLAY := "res://game/config/gameplay/gameplay.json5"
const CFG_VISUALS := "res://game/config/performance/visuals.json5"
const CFG_SYSTEM := "res://game/config/performance/system.json5"
const CFG_WEAPONS := "res://game/config/entities/weapons.json5"
const CFG_WEAPON_ADJUSTMENTS := "res://game/config/gameplay/weapon_adjustments.json5"
